name: ci

on:
  push:
    branches: [main]
    paths: ["runtime/**", ".github/workflows/ci.yml"]
  pull_request:
    paths: ["runtime/**", ".github/workflows/ci.yml"]
  workflow_dispatch:
    inputs:
      publishDev:
        description: 'Publish dev image as {sha}'
        required: true
        default: false
        type: boolean

permissions:
  id-token: write
  contents: read

jobs:
  check-lock:
    name: Check lockfile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v3

      - uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.24"

      - name: Check if lockfile is up to date
        run: |
          just lock-check

  decide:
    name: Decide if image should be published
    runs-on: ubuntu-latest
    outputs:
      should_publish: ${{ steps.decide.outputs.should_publish }}
      should_publish_latest: ${{ steps.decide.outputs.should_publish_latest }}
      env_name: ${{ steps.decide.outputs.env_name }}
    steps:
      - id: decide
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" && "${{ vars.PUBLISH_LATEST_ON_MAIN }}" != "" ]]; then
            should_publish=true
            should_publish_latest=true
            env_name=production
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ inputs.publishDev }}" == "true" ]]; then
            should_publish=true
            should_publish_latest=false
            env_name=production
          else
            should_publish=false
            should_publish_latest=false
            env_name=dev
          fi
          {
            echo "should_publish=$should_publish"
            echo "should_publish_latest=$should_publish_latest"
            echo "env_name=$env_name"
          } | tee -a "$GITHUB_OUTPUT"

  build:
    name: Build
    needs: [check-lock, decide]
    runs-on:
      labels: kids-asr-ubuntu-24.04-4core
    environment:
      name: ${{ needs.decide.outputs.env_name }}
    env:
      LOGIN_SERVER: kidsasrprodacr.azurecr.io
      IMAGE_NAME: kids-asr-runtime
      SHA_TAG: ${{ github.sha }}
      LATEST_TAG: latest

    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v3

      - name: Disk information
        run: |
          df -h

      - name: Build test image
        run: |
          just test-build

      - name: Run tests in test image
        run: |
          just test-run

      - name: Build runtime image
        run: |
          just build \
            --tag $LOGIN_SERVER/$IMAGE_NAME:$SHA_TAG \

      - name: Tag as latest
        if: ${{ needs.decide.outputs.should_publish_latest == 'true' }}
        run: |
          docker tag $LOGIN_SERVER/$IMAGE_NAME:$SHA_TAG $LOGIN_SERVER/$IMAGE_NAME:$LATEST_TAG

      - name: Check image size
        run: |
          docker image list $LOGIN_SERVER/$IMAGE_NAME --format "{{.Tag}}: {{.Size}}" | tee -a $GITHUB_STEP_SUMMARY

      - name: Log into Azure
        if: ${{ needs.decide.outputs.should_publish == 'true' }}
        uses: azure/login@v1
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

      - name: Log into ACR
        if: ${{ needs.decide.outputs.should_publish == 'true' }}
        run: |
          az acr login --name $LOGIN_SERVER

      - name: Push image to ACR
        if: ${{ needs.decide.outputs.should_publish == 'true' }}
        run: |
          docker push $LOGIN_SERVER/$IMAGE_NAME --all-tags
