name: ci

on:
  push:
    branches: [main]
    paths: ["runtime/**", ".github/workflows/ci.yml"]
  pull_request:
    paths: ["runtime/**", ".github/workflows/ci.yml"]
  workflow_dispatch:
    inputs:
      publishDev:
        description: 'Publish dev image as {sha}'
        required: true
        default: false
        type: boolean

permissions:
  id-token: write
  contents: read

jobs:
  check-lock:
    name: Check lockfile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v3

      - uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.24"

      - name: Check lockfile
        run: |
          just lock-check

  build:
    name: Build
    needs: check-lock
    runs-on:
      labels: kids-asr-ubuntu-24.04-4core
    env:
      SHOULD_PUBLISH_LATEST: ${{ github.ref == 'refs/heads/main' && vars.PUBLISH_LATEST_ON_MAIN != '' }}
      SHOULD_PUBLISH: |
        ${{
          github.ref == 'refs/heads/main' && vars.PUBLISH_LATEST_ON_MAIN != ''
          || github.event_name == 'workflow_dispatch' && inputs.publishDev
        }}
      LOGIN_SERVER: kidsasrprodacr.azurecr.io
      IMAGE_NAME: kids-asr-runtime
      SHA_TAG: ${{ github.sha }}
      LATEST_TAG: latest

    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v3

      - name: Disk information
        run: |
          df -h

      - name: Build test image
        run: |
          just test-build

      - name: Run tests in test image
        run: |
          just test-run

      - name: Build runtime image
        run: |
          just build \
            --tag $LOGIN_SERVER/$IMAGE_NAME:$SHA_TAG \
            ${{ fromJson(env.SHOULD_PUBLISH_LATEST) && '--tag $LOGIN_SERVER/$IMAGE_NAME:$LATEST_TAG' || '' }}

      - name: Check image size
        run: |
          docker image list $LOGIN_SERVER/$IMAGE_NAME --format "{{.Tag}}: {{.Size}}" | tee -a $GITHUB_STEP_SUMMARY

      - name: Log into Azure
        if: ${{ fromJson(env.SHOULD_PUBLISH) }}
        uses: azure/login@v1
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

      - name: Log into ACR
        if: ${{ fromJson(env.SHOULD_PUBLISH) }}
        run: |
          az acr login --name $LOGIN_SERVER

      - name: Push image to ACR
        if: ${{ fromJson(env.SHOULD_PUBLISH) }}
        run: |
          docker push $LOGIN_SERVER/$IMAGE_NAME --all-tags
